### ISSUE TITLE
short:"p"

### ISSUE THREAD

**Issue by axet** [anacrolix/tagflag#1]
short:"p" not actually works. keyword just ignored.

**Comment by anacrolix** [comment]
I'll take a look. Any particular package main giving you this?

**Comment by axet** [comment]
I'm trying to update torrent/cmd/torrent-create with '-a' option to specify annonce server

https://github.com/axet/gotorrent/commit/229e6a73f783ccb427d11bad300e04a95d308c83

Also, passing option as

-annonceList udp://..

gives an error, it require '=' after option.

**Comment by anacrolix** [comment]
Sorry the package isn't well documented, it's still an experiment. The tag you want is `name`. `name:"a"`.

It's spelt "announce".

I've changed the way it parses flags, flags must always be of the form `-flag=value`. There's reasons for that decision but it mainly has to do with bool flags and not wanting to complicate it.

**Comment by anacrolix** [comment]
Also rather than support both long and short flags, it just builds a default one from the struct field, unless `name` is specified. Fortunately the builtin help is quite nice.

**Comment by anacrolix** [comment]
I gather this is addressed since the pull request in anacrolix/torrent.

**Comment by axet** [comment]
Not really important but I found short"p" in torrent cmd.

https://github.com/anacrolix/torrent/blob/master/cmd/torrent/main.go

**Comment by anacrolix** [comment]
Thanks I removed that.
